sudo: required
services:
  - docker

before_install:
  - docker build -t fabriciouehara/docker-react -f Dockerfile.dev .

script:
  - uname -a
  - docker version
  - whoami
  - hostname
  - ifconfig
  - docker run -e CI=true fabriciouehara/docker-react npm run test -- --coverage

