sudo: required
services:
  - docker

before_install:
  - docker build -t fabriciouehara/docker-react -f Dockerfile.dev .

script:
  - uname -a
  - docker version
  - whoami
  - hostname
  - ifconfig
  - docker run -e CI=true fabriciouehara/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-796880136785"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
