sudo: required
services:
  - docker

before_install:
  - docker build -t fabriciouehara/docker-react -f Dockerfile.dev .

script:
  - uname -a
  - docker run fabriciouehara/docker-react npm run test -- --coverage

